en:
    description-title: Knowledge Portal
    description-text: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy textthe 1500s."
    login-title: Login to your account
    login-button: LOGIN
    username-placeholder: Username
    password-placeholder: Password2
    show-login-form-button: Login to your account

fr:
    description-title: Knowledge Portal
    description-text: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy textthe 1500s."
    login-title: Login to your account
    login-button: LOGIN
    username-placeholder: Username2
    password-placeholder: Password
    show-login-form-button: Login to your account